version: '3'

services:
    workshop:
        container_name: phpschool-learnyouphp
        image: phpschool/learn-you-php
        volumes:
            - $PHPSCHOOL_CODE_DIR/learnyouphp:/phpschool:rw
        stdin_open: true
        tty: true
